[package]
name = "mudssky_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = [
    "time",
    "rt",
    "rt-multi-thread",
    "macros",
] }
regex = "1.11.1"
