[package]
name = "mudssky_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
tokio = { version = "1.46", features = ["full"] }
regex = "1.11"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
